/run/numberOfThreads 1 

/construction/detector/option 0

/analysis/setFileName visualization

/run/initialize

/vis/open OGL

/vis/viewer/set/viewpointVector 1 0 0 # Sets initial view when sim opened
/vis/viewer/set/autoRefresh true # Update UI after every event

/vis/drawVolume # Draw all volumes

/vis/scene/add/trajectories smooth
/vis/scene/add/endOfEventAction/accumulate
/vis/scene/add/scale 10 cm
/vis/scene/add/eventID